

render_config:
  model_path: "http://localhost:8082/tileset.json"
  init_rot: [49.71794737193199, 0, 131.18351655093858]
  init_trans: [113.00487144412334, 28.291504331699095, 72.80589840188622]
  # render_camera: [960, 540, 689.475, 689.45,478.75, 268.35]
  outputs: "outputs/citystars"
default_confs:
  from_render_test:
    checkpoint: "/mnt/sda/MapScape/Pretrained_model/model@mapscape@512@Fourier.ckpt"
    refinement:
      num_dbs: 3
      multiscale: [4, 1]
      point_selection: "all"
      normalize_descriptors: true
      average_observations: false
      do_pose_approximation: true
    optimizer:
      ratio: 2.55
      num_iters: 3
      pad: 1
      lambda_: 0.01
      verbose: false
      loss_fn: scaled_barron(0, 0.1)
      no_conditions: true
      jacobi_scaling: false
      sqrt_diag_damping: false
      name: learned_optimizer
      bound_confidence: true
      learned_damping: true
      damping:
        type: constant
    init_target_offset: null
    success_thresh: 3
    name: two_view_refiner
    normalize_features: true
    duplicate_optimizer_per_scale: true
    features:
      conf:
    scales: [1, 2, 4]
    extractor:
      name: unet_fusion
      # num_head: 1
      num_output_layer: 3 # 4 # 3
      output_dim: [32, 32, 32] # [31, 31, 31] # [15, 15, 15] # [15, 15, 15, 15] # [16, 16, 16, 16] # [16, 16, 16]
      encoder: mobileone_s0 # 'mobileone_s0' # mobileone_s1 # mobilenet_v2 tu-mobilevit_xs
      encoder_depth: 3 # 4 # 3 # 5
      decoder: UnetDecoder
      decoder_channels: [128, 64, 32] # [128, 64, 32, 16] # [128, 64, 32] # [256, 128, 64, 32, 16]
      align_data_to_pretrain: false # false # true
      pretrained_weights: "imagenet"
      train_mask: false # true # false
      normalize_key: false # true # false
      train_box: false # true
      compute_uncertainty: true
      trainable: true # false # true

  cam_query:
    max_size: 960
    model: "PINHOLE"

    width: 2448
    height: 2048
    # params:
    #   [
    #     1478.055419921875,
    #     1478.055419921875,
    #     1176.0584117437975,
    #     1047.5184035578786,
    #   ]
    params:
      [1481.705078125, 1481.705078125, 1175.9687937450362, 1050.2202901721903]

    distortion: []

  dataset_path: "/mnt/sda/MapScape/query"
  dataset_name: "interval1_HKairport_GNSS03"
  output_name: "interval1_HKairport_GNSS03"
  use_kf: false
  padding: True
  refine:
    origin: [0, 0, 0]
    dis_thes: 10
    R_thes: 20
    mul: 0.001
  num_init_pose: 64
